blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/PUwSMR9XNk
    about: Join the community for real-time discussion around the research workflow remake
