export const PACKAGE_NAME = "@johanjohnthomas/oh-my-research"
export const LEGACY_PACKAGE_NAME = "oh-my-research"
export const PLUGIN_NAME = "oh-my-research"
export const LEGACY_PLUGIN_NAME = "oh-my-opencode"
export const CONFIG_BASENAME = "oh-my-research"
export const LEGACY_CONFIG_BASENAME = "oh-my-opencode"
export const LOG_FILENAME = "oh-my-research.log"
export const CACHE_DIR_NAME = "oh-my-research"
